<?php

return [
    'trusted_domains' => ['*'],
    'datadirectory' => '/mnt/data/files',
    'dbtype' => 'mysql',
    'dbhost' => 'DB:3306',
    'dbname' => 'owncloud',
    'dbuser' => 'owncloud',
    'dbpassword' => 'owncloud',
    'dbtableprefix' => 'oc_',
    'log_type' => 'owncloud',
    'supportedDatabases' => ['sqlite', 'mysql', 'pgsql'],
    'upgrade.disable-web' => true,
    'default_language' => 'en',
    'overwrite.cli.url' => 'http://localhost/',
    'htaccess.RewriteBase' => '/',
    'logfile' => '/mnt/data/files/owncloud.log',
    'memcache.local' => '\\OC\\Memcache\\APCu',
    'filelocking.enabled' => true,
    'passwordsalt' => 'v4lLJG1c/uyMwGP89VS6kQ2rpTIRYm',
    'secret' => 'KW/NpppTQ2mmdClw5b/6VnhJCpm9haWgGjCkRQzMk55dAjI1',
    'version' => '10.14.0.3',
    'dbconnectionstring' => '',
    'mysql.utf8mb4' => true,
    'allow_user_to_change_mail_address' => '',
    'logtimezone' => 'UTC',
    'installed' => true,
    'instanceid' => 'ocdo1d7sbpyh',
];
