version : "3"
# Spécifie la version de la syntaxe Docker compose que nous utilisons

services:
# Cette section définit les services que nous voulons exécuter à l'aide de Docker compose
  db:
    image: mysql:5.7
    # définit le service de la BDD : Mysql version 5.7
    container_name: owncloud-mysql
    # nom du conteneur pour le service de la BDD
    restart: always
    # cette instruction spécifie que le conteneur doit redémarrer automatiquement
    # en cas d'échec ou d'arrêt
    environment:
      MYSQL_DATABASE: owncloud
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: owncloud
      MYSQL_ROOT_PASSWORD: rootpassword
      # définit les variables d'environnement pour configurer la BDD MYSQL.
    volumes:
      - db-data:/var/lib/mysql
      # nous montons un volume Docker pour persister les données de la BDD mysql
      # sur le système hôte.
  
  owncloud:
    image: owncloud/server
    # définit le service owncloud. Nous utilisons l'image Docker officielle OwnCloud
    container_name: owncloud
    # nom du conteneur
    restart: always
    # même chose

    ports:
      - "8080:8080"
      # mappe le port 8080 du conteneur OwnCloud sur le port 8080 de l'hôte.
    depends_on:
      - db
      # spécifie que le service Owncloud dépend du service de BDD. Cela garantie
      # que le service de BDD démarrer avant le service OwnCloud.
    environment:
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: owncloud
      OWNCLOUD_DB_USERNAME: owncloud
      OWNCLOUD_DB_PASSWORD: owncloud 
      OWNCLOUD_DB_HOST: DB
      # variables d'environnement sont utilisées pour configurer OwnCloud pour qu'il utilise
      # la BDD MYSQL. Type de BDD, nom de la BDD, nom d'utilisateur, mdp et nom d'hôte.
    volumes:
    - owncloud-data:/var/www/html
    # on monte un volume Docker pour persister les données Owncloud sur le système hôte



volumes:
  db-data:
  owncloud-data:

  # dans cette section, on définit les volumes Docker que nous avons utilisé
  # dans nos services